#jdbc:
#  driverClassName: com.mysql.jdbc.Driver
#  url: jdbc:mysql://localhost:33060/ssm?useUnicode=true&characterEncoding=utf8
#  username: homestead
#  password: secret

server:
  port: 8090
  servlet:
    path: /

# 日志级别
logging:
  level:
    # 键值对形式
      #键: 包名
      #值: 日志级别
    hyder: debug
#    org.springframework: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:33060/ssm
    username: homestead
    password: secret

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: hyder.pojo

#  mapper-locations: mapper/*.xml
